# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ui_bmstu.ui'
#
# Created by: PyQt5 UI code generator 5.15.10
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(800, 598)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.address = QtWidgets.QTextEdit(self.centralwidget)
        self.address.setGeometry(QtCore.QRect(260, 130, 221, 31))
        self.address.setObjectName("address")
        self.password = QtWidgets.QTextEdit(self.centralwidget)
        self.password.setGeometry(QtCore.QRect(260, 190, 221, 31))
        self.password.setObjectName("password")
        self.login = QtWidgets.QPushButton(self.centralwidget)
        self.login.setGeometry(QtCore.QRect(260, 230, 121, 41))
        self.login.setObjectName("login")
        self.first_timelabel = QtWidgets.QLabel(self.centralwidget)
        self.first_timelabel.setGeometry(QtCore.QRect(270, 270, 101, 16))
        self.first_timelabel.setObjectName("first_timelabel")
        self.registration = QtWidgets.QPushButton(self.centralwidget)
        self.registration.setGeometry(QtCore.QRect(260, 290, 121, 41))
        self.registration.setObjectName("registration")
        self.password_label = QtWidgets.QLabel(self.centralwidget)
        self.password_label.setGeometry(QtCore.QRect(270, 170, 211, 16))
        self.password_label.setObjectName("password_label")
        self.address_label = QtWidgets.QLabel(self.centralwidget)
        self.address_label.setGeometry(QtCore.QRect(270, 110, 211, 16))
        self.address_label.setObjectName("address_label")
        self.fio = QtWidgets.QTextEdit(self.centralwidget)
        self.fio.setGeometry(QtCore.QRect(260, 240, 221, 31))
        self.fio.setObjectName("fio")
        self.group = QtWidgets.QTextEdit(self.centralwidget)
        self.group.setGeometry(QtCore.QRect(260, 290, 221, 31))
        self.group.setObjectName("group")
        self.fio_label = QtWidgets.QLabel(self.centralwidget)
        self.fio_label.setGeometry(QtCore.QRect(270, 220, 211, 16))
        self.fio_label.setObjectName("fio_label")
        self.group_label = QtWidgets.QLabel(self.centralwidget)
        self.group_label.setGeometry(QtCore.QRect(270, 270, 211, 16))
        self.group_label.setObjectName("group_label")
        self.toregister = QtWidgets.QPushButton(self.centralwidget)
        self.toregister.setGeometry(QtCore.QRect(260, 330, 171, 41))
        self.toregister.setObjectName("toregister")
        self.mgtu_logo = QtWidgets.QLabel(self.centralwidget)
        self.mgtu_logo.setGeometry(QtCore.QRect(500, 100, 91, 101))
        self.mgtu_logo.setText("")
        self.mgtu_logo.setObjectName("mgtu_logo")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 800, 24))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.login.setText(_translate("MainWindow", "Войти"))
        self.first_timelabel.setText(_translate("MainWindow", "Впервые?"))
        self.registration.setText(_translate("MainWindow", "Регистрация"))
        self.password_label.setText(_translate("MainWindow", "Пароль"))
        self.address_label.setText(_translate("MainWindow", "Почта"))
        self.fio_label.setText(_translate("MainWindow", "ФИО"))
        self.group_label.setText(_translate("MainWindow", "Группа (пример: ИУ3-23Б)"))
        self.toregister.setText(_translate("MainWindow", "Зарегистрироваться"))
